Console.Clear();
Console.WriteLine("salam man fereshteh hastam 34 salame va daneshju hastam");
await Task.Delay(2000);
Console.Beep(1000,200);
Console.Beep(5000,200);
Console.Beep(3000,200);
Console.Beep(2000,200);
Console.ForegroundColor=ConsoleColor.Green;
Console.WriteLine("mikhay beduni shoqlam chie?");
Console.WriteLine("ye kilid ro feshar bede");
Console.ReadKey(true);
Console.BackgroundColor=ConsoleColor.Yellow;
await Task.Delay(5000);
Console.WriteLine("afariiin");
Console.WriteLine("vali nemigam chon shakhsie");
Console.WriteLine("shokhi kardam\nbehetun migam");
Console.Write("man hododan 8 sal sabeghe kar dar markaze darmani ro daram");
await Task.Delay(3000);
Console.BackgroundColor=ConsoleColor.Blue;
Console.WriteLine("\nye dokmeye dg bezan lotfan");
Console.ReadKey(true);
Console.BackgroundColor=ConsoleColor.Green;
Console.WriteLine("karmande bakhshe edari budam");
Console.Beep(2000,100);
Console.Beep(3000,200);
Console.Beep(3000,100);
Console.Beep(5000,200);
Console.Beep(2000,200);
Console.ForegroundColor=ConsoleColor.Red;
Console.WriteLine(@"time karim kheili sangin bud chon tamamie karhaye bimei ba khodam bud");
await Task.Delay(3000);
Console.WriteLine("karamo dus dashtam vali yejayi kam avordam va estefa dadam");
Console.WriteLine("bad az on tasmim gereftam darsamo edame bedam");
Console.BackgroundColor=ConsoleColor.Yellow;
Console.WriteLine("kenare dars varzesh kardam");

